// AUTO-GENERATED by scripts/gen-mdx-types.ts — DO NOT EDIT
// Regenerate: bun scripts/gen-mdx-types.ts
//
// Typed declarations for 8 MDX prompt files.
// Props extracted from remark-mdx AST expression nodes,
// so `tsc --noEmit` catches wrong names, missing props, and extras.

declare module "*/prompts/CodeReview.mdx" {
  interface CodeReviewPromptProps {
    filesCreated?: any;
    filesModified?: any;
    qualityChecks?: any;
    unitCategory: any;
    unitId: any;
    unitName: any;
    whatWasDone?: any;
  }
  const Component: import("react").FC<CodeReviewPromptProps>;
  export default Component;
}

declare module "*/prompts/FinalReview.mdx" {
  interface FinalReviewPromptProps {
    acceptanceCriteria?: any;
    antiSlopFlags?: any;
    believesComplete?: any;
    boundedContext: any;
    buildPassed?: any;
    codeApproved?: any;
    codeSeverity?: any;
    description: any;
    domainInvariants?: any;
    failingSummary?: any;
    gherkinFeature: any;
    gherkinScenarios?: any;
    implSummary?: any;
    issuesResolved?: any;
    maxPasses: any;
    pass: any;
    prdApproved?: any;
    prdSeverity?: any;
    scenariosCovered?: any;
    scenariosTotal?: any;
    tddEvidence?: any;
    testsFailCount?: any;
    testsPassCount?: any;
    traceCompleteness?: any;
    uncoveredScenarios?: any;
    unitId: any;
    unitName: any;
  }
  const Component: import("react").FC<FinalReviewPromptProps>;
  export default Component;
}

declare module "*/prompts/Implement.mdx" {
  interface ImplementPromptProps {
    acceptanceCriteria?: any;
    architectureRules?: any;
    boundedContext: any;
    branchPrefix?: any;
    commitPrefix?: any;
    contextFilePath: any;
    depSummaries?: any;
    domainInvariants?: any;
    emojiPrefixes?: any;
    evictionContext?: any;
    failingTests?: any;
    formatterCommands?: any;
    gherkinFeature: any;
    gherkinScenarios?: any;
    implementationGuidance?: any;
    implementationSteps?: any;
    planFilePath: any;
    previousImplementation?: any;
    reviewFeedback?: any;
    testWritingGuidance?: any;
    ubiquitousLanguage?: any;
    unitCategory: any;
    unitId: any;
    unitName: any;
    verifyCommands?: any;
  }
  const Component: import("react").FC<ImplementPromptProps>;
  export default Component;
}

declare module "*/prompts/Plan.mdx" {
  interface PlanPromptProps {
    acceptanceCriteria?: any;
    boundedContext: any;
    branchPrefix?: any;
    commitPrefix?: any;
    contextFilePath: any;
    domainInvariants?: any;
    evictionContext?: any;
    gherkinFeature: any;
    gherkinScenarios?: any;
    planFilePath: any;
    researchSummary?: any;
    tddPatterns?: any;
    ubiquitousLanguage?: any;
    unitCategory: any;
    unitDescription: any;
    unitId: any;
    unitName: any;
  }
  const Component: import("react").FC<PlanPromptProps>;
  export default Component;
}

declare module "*/prompts/PrdReview.mdx" {
  interface PrdReviewPromptProps {
    acceptanceCriteria?: any;
    boundedContext: any;
    domainInvariants?: any;
    failingSummary?: any;
    filesCreated?: any;
    filesModified?: any;
    gherkinFeature: any;
    gherkinScenarios?: any;
    scenariosCovered?: any;
    scenariosTotal: any;
    specChecks?: any;
    testResults?: any;
    ubiquitousLanguage?: any;
    uncoveredScenarios?: any;
    unitCategory: any;
    unitId: any;
    unitName: any;
  }
  const Component: import("react").FC<PrdReviewPromptProps>;
  export default Component;
}

declare module "*/prompts/Research.mdx" {
  interface ResearchPromptProps {
    boundedContext: any;
    branchPrefix?: any;
    contextFilePath: any;
    domainInvariants?: any;
    evictionContext?: any;
    gherkinFeature: any;
    gherkinScenarios?: any;
    referenceFiles?: any;
    referencePaths?: any;
    relevantFiles?: any;
    rfcSections?: any;
    rfcSource?: any;
    ubiquitousLanguage?: any;
    unitCategory: any;
    unitDescription: any;
    unitId: any;
    unitName: any;
  }
  const Component: import("react").FC<ResearchPromptProps>;
  export default Component;
}

declare module "*/prompts/ReviewFix.mdx" {
  interface ReviewFixPromptProps {
    branchPrefix?: any;
    codeFeedback: any;
    codeIssues?: any;
    codeSeverity: any;
    commitPrefix?: any;
    emojiPrefixes?: any;
    specFeedback: any;
    specIssues?: any;
    specSeverity: any;
    unitCategory: any;
    unitId: any;
    unitName: any;
    validationCommands?: any;
  }
  const Component: import("react").FC<ReviewFixPromptProps>;
  export default Component;
}

declare module "*/prompts/Test.mdx" {
  interface TestPromptProps {
    branchPrefix?: any;
    domainInvariants?: any;
    filesCreated?: any;
    filesModified?: any;
    fixCommitPrefix?: any;
    gherkinFeature: any;
    gherkinScenarios?: any;
    testSuites?: any;
    unitCategory: any;
    unitId: any;
    unitName: any;
    whatWasDone?: any;
  }
  const Component: import("react").FC<TestPromptProps>;
  export default Component;
}
